# Generated by Django 4.0.5 on 2022-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
