# Generated by Django 4.0.5 on 2022-07-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0002_user_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
