# Generated by Django 4.0.5 on 2022-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0004_user_is_verified_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_num', models.IntegerField()),
                ('release_desc', models.TextField()),
            ],
        ),
    ]
