# Generated by Django 4.0.5 on 2022-07-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0006_card_release_num_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Release',
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('epic', models.CharField(max_length=255)),
                ('scope_desc', models.TextField()),
                ('release_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.release')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.user')),
            ],
        ),
    ]
