# Generated by Django 4.0.5 on 2022-07-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0008_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='scope_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.scope'),
            preserve_default=False,
        ),
    ]
