# Generated by Django 4.0.5 on 2022-07-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0009_testcase_scope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
