# Generated by Django 4.0.5 on 2022-07-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0010_testcase_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='id',
            new_name='pkk',
        ),
    ]
