# Generated by Django 4.0.5 on 2022-07-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0011_rename_id_release_pkk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='release_id',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='scope_id',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tc_author',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tester_android',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tester_automation',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tester_be',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tester_internal',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tester_ios',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tester_portal',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tester_rm',
        ),
        migrations.DeleteModel(
            name='Release',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
