# Generated by Django 4.0.5 on 2022-07-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myfirsttry', '0012_remove_scope_release_id_remove_scope_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_num', models.IntegerField()),
                ('release_num_word', models.CharField(max_length=50)),
                ('release_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('epic', models.CharField(max_length=255)),
                ('scope_desc', models.TextField()),
                ('release_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.release')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usecase', models.CharField(max_length=200)),
                ('steps', models.TextField()),
                ('expected_result', models.TextField()),
                ('ts_portal', models.CharField(max_length=15)),
                ('ts_rm', models.CharField(max_length=15)),
                ('ts_internal', models.CharField(max_length=15)),
                ('ts_be', models.CharField(max_length=15)),
                ('ts_ios', models.CharField(max_length=15)),
                ('ts_android', models.CharField(max_length=15)),
                ('ts_automation', models.CharField(max_length=15)),
                ('tester_comment', models.TextField()),
                ('reviewer_comment', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('scope_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.scope')),
                ('tc_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tc_author', to='myfirsttry.user')),
                ('tester_android', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_android', to='myfirsttry.user')),
                ('tester_automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_automation', to='myfirsttry.user')),
                ('tester_be', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_be', to='myfirsttry.user')),
                ('tester_internal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_internal', to='myfirsttry.user')),
                ('tester_ios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_ios', to='myfirsttry.user')),
                ('tester_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_portal', to='myfirsttry.user')),
                ('tester_rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_rm', to='myfirsttry.user')),
            ],
        ),
        migrations.AddField(
            model_name='scope',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.user'),
        ),
    ]
