# Generated by Django 4.0.5 on 2022-07-29 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0013_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='reviewer_comment',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='scope_id',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tc_author',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='tester_comment',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='title',
        ),
        migrations.CreateModel(
            name='TestCase_Title',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('scope_id', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('tc_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tc_author', to='myfirsttry.user')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='title_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.testcase_title'),
            preserve_default=False,
        ),
    ]
