# Generated by Django 4.0.5 on 2022-07-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0015_remove_testcase_title_tc_author_delete_testcase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase_Title',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('tc_author', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('scope_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.scope')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usecase', models.CharField(max_length=200)),
                ('steps', models.TextField()),
                ('expected_result', models.TextField()),
                ('ts_portal', models.CharField(max_length=15)),
                ('ts_rm', models.CharField(max_length=15)),
                ('ts_internal', models.CharField(max_length=15)),
                ('ts_be', models.CharField(max_length=15)),
                ('ts_ios', models.CharField(max_length=15)),
                ('ts_android', models.CharField(max_length=15)),
                ('ts_automation', models.CharField(max_length=15)),
                ('comment', models.TextField()),
                ('tester_android', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_android', to='myfirsttry.user')),
                ('tester_automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_automation', to='myfirsttry.user')),
                ('tester_be', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_be', to='myfirsttry.user')),
                ('tester_internal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_internal', to='myfirsttry.user')),
                ('tester_ios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_ios', to='myfirsttry.user')),
                ('tester_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_portal', to='myfirsttry.user')),
                ('tester_rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_rm', to='myfirsttry.user')),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.testcase_title')),
            ],
        ),
    ]
