# Generated by Django 4.0.5 on 2022-07-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttry', '0016_testcase_title_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='tester_android',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester_android', to='myfirsttry.user'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tester_automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester_automation', to='myfirsttry.user'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tester_be',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester_be', to='myfirsttry.user'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tester_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester_internal', to='myfirsttry.user'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tester_ios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester_ios', to='myfirsttry.user'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tester_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester_portal', to='myfirsttry.user'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tester_rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester_rm', to='myfirsttry.user'),
        ),
        migrations.AlterField(
            model_name='testcase_title',
            name='scope_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfirsttry.scope'),
        ),
    ]
